Repository AkhlaqAltaf/TrainingToFirnasStds, pull requests merged in 2024-08, with the labels that each got.

#8 DATA COLLECTION WEB SCRAPING EXAMPLE
  lecture4/readme.md
  lecture4/webscraping.ipynb
Labels: Updates

#7 Hamad470 patch 3
  lecture3/data_cleaning&pre_processing/data_cleaning&preprocessing(hamad).ipynb
  lecture3/data_cleaning&pre_processing/merged.csv
  lecture3/data_cleaning&pre_processing/output5.csv
  lecture3/data_cleaning&pre_processing/output6.csv
  lecture3/data_cleaning&pre_processing/output6.zip
  lecture3/data_cleaning&pre_processing/output7.csv
  lecture3/data_cleaning&pre_processing/output8.csv
  lecture3/data_collection/scraping.ipynb
Labels: enhancement

#9 FETCHING WIKIPEDIA DATASET
  lecture4/scrapwiki.ipynb
Labels: enhancement

#10 Enhance Structure Of Lectures
  lecture4/scraping_beautifulsoup.ipynb
  lecture4/scrapwiki.ipynb
Labels: enhancement

#13 custom linear regression
  lecture3/data_collection/SocialMedia.docx
  lecture3/data_collection/logs_file
  lecture5/linear_reg_custom(Hamad).ipynb
Labels: enhancement

#14 Hamad470 patch 3
  lecture5/houseSale(Hamad).ipynb
  lecture5/linear_reg_custom(Hamad).ipynb
  lecture5/linear_reg_official formula(Hamad) .ipynb
  lecture5/multilinear_regression(Hamad).ipynb
  lecture5/sk_lin_reg(Hamad).ipynb
Labels: enhancement

#15 Hamad470 patch 3
  lecture5/gradientDescent.ipynb
  lecture5/linear_reg_custom(Hamad).ipynb
  lecture5/mult-l-reg-own-f(Hamad).ipynb
  lecture5/multilinear_regression(Hamad).ipynb
  lecture5/pic1-result.png
Labels: enhancement

#19 Hamad470 patch 3
  lecture5/KNN_custom(Hamad).ipynb
  lecture5/mult-l-reg-own-f(Hamad).ipynb
  lecture6/houseSale(Hamad).ipynb
  lecture6/linear_reg_custom(Hamad).ipynb
  lecture6/linear_reg_official formula(Hamad) .ipynb
Labels: enhancement

#32 FOR 22-8-2024 Leactures Prepared 1.Ensemble Models 2.Logistic Regres…
  lecture13/ensemble_techniques.ipynb
  lecture13/random_forest.ipynb
  lecture13/readme.md
  lecture14/logistic_regression.ipynb
  lecture14/readme.md
  lecture9/readme.md
  python/classes.py
  python/programing_beginers/lecture1.py
  python/programing_beginers/lecture2/data_types.py
  python/programing_beginers/lecture2/readme.md
Labels: Task Created

#29 Decision tree on iris dataset
  lecture12/anime.ipynb
  lecture12/decison_tree(Hamad).ipynb
  lecture12/digit classification(Hamad).ipynb
Labels: enhancement
